version: "3.2"

volumes:
  nextcloud:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/davidzz/nc/html
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/davidzz/nc/mysql
  files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mypool/img

services:
  db:
    image: mariadb:10.5.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - mysql_root_password
      - mysql_password

  app:
    image: nextcloud:22-apache
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - files:/mydata
    environment:
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_DATA_DIR=/mydata
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.132,192.168.1.156,192.168.1.131
    secrets:
      - nextcloud_admin_user
      - nextcloud_admin_password
      - mysql_root_password
      - mysql_password

secrets:
  nextcloud_admin_user:
    file: ./passwords/NEXTCLOUD_ADMIN_USER
  nextcloud_admin_password:
    file: ./passwords/NEXTCLOUD_ADMIN_PASSWORD
  mysql_root_password:
    file: ./passwords/MYSQL_ROOT_PASSWORD
  mysql_password:
    file: ./passwords/MYSQL_PASSWORD
